Numerical python which is also know as Numpy is used for numerical value its most probably 50x faster normal python list that's why we use numpy further in our data analytics and Ml
it was created in 2005 by travis oliphant is deep down written in c and c++ 

In [2]:
import numpy as np
#here we import our numpy library

In [10]:
#numpy array
arr = np.array([12,45,78,90,87])
print(arr[3])

90


In [14]:
arr = np.array([12,45,78,90,87])
print(arr[1:])

[45 78 90 87]


In [24]:
arr = np.array([12,45,78,90,87])
print(arr.ndim)
# print(arr[:2])

1


In [26]:
ar1 = np.array([[1,2,3],[4,5,6]])
# print(ar1.ndim)
# print(type(ar1))
print(ar1)

[[1 2 3]
 [4 5 6]]
