Numerical python which is also know as Numpy is used for numerical value its most probably 50x faster normal python list that's why we use numpy further in our data analytics and Ml
it was created in 2005 by travis oliphant is deep down written in c and c++ 

In [1]:
import numpy as np
#here we import our numpy library

Numpy Basic Array And Index Slicing

In [10]:
#numpy array
arr = np.array([12,45,78,90,87])
print(arr[3])

90


1-D Array

In [14]:
arr = np.array([12,45,78,90,87])
print(arr[1:])

[45 78 90 87]


In [24]:
arr = np.array([12,45,78,90,87])
print(arr.ndim)
# print(arr[:2])

1


2-D Array

In [3]:
ar1 = np.array([[23,45,87,88],[91,54,61,32]])
print(ar1.ndim)
print(ar1[1][0])

2
91


In [8]:
ar2=np.array([[[1,2,3,4],[5,6,7,8]],   [[9,10,11,12],[13,14,15,16]]])
print(ar2.ndim)
print(ar2[1][0][1])
print(ar2[1][1][2])
print(ar2[1][0][2])
print(ar2[1][1][1])

3
10
15
11
14


Statstical Operation

In [ ]:
arr3 = np.array([21,22,65,89,11,32])
np.sum(arr3)   #total number
np.mean(arr3)  #when we have to calculate the average data
np.max(arr3)  #when we want to get maximum value
np.min(arr3)   #when we want to get minimum value

np.int64(11)

Mathematical Operations

In [13]:
a = np.array([23,11,13,14])
b = np.array([20,10,9,12])


In [14]:
np.add(a,b)

array([43, 21, 22, 26])

In [15]:
np.subtract(a,b)

array([3, 1, 4, 2])

In [16]:
np.multiply(a,b)

array([460, 110, 117, 168])

In [17]:
np.divide(a,b)

array([1.15      , 1.1       , 1.44444444, 1.16666667])

In [ ]:
np.power(a,2)  #when we want to find square
np.power(a,3)    #when we want to find cube

array([12167,  1331,  2197,  2744])

In [20]:
np.sqrt(a)

array([4.79583152, 3.31662479, 3.60555128, 3.74165739])